-- =====================================================
-- CineManager - Criação do banco/tabelas
--
-- Observação:
-- No Supabase, o projeto já possui um banco criado.
-- Por isso, aqui criamos apenas as tabelas.
-- =====================================================

drop table if exists public.ingressos;
drop table if exists public.sessoes;
drop table if exists public.clientes;
drop table if exists public.filmes;

create table public.filmes (
    id_filme integer generated by default as identity,
    titulo varchar(150) not null,
    genero varchar(80) not null,
    duracao integer not null,
    classificacao varchar(10) not null,
    diretor varchar(120) not null,

    constraint pk_filmes primary key (id_filme),
    constraint chk_filmes_duracao check (duracao > 0),
    constraint chk_filmes_classificacao check (classificacao in ('Livre', '10', '12', '14', '16', '18'))
);

create table public.sessoes (
    id_sessao integer generated by default as identity,
    id_filme integer not null,
    data_hora timestamp not null,
    sala integer not null,
    preco numeric(10, 2) not null,
    ingressos_vendidos integer not null default 0,

    constraint pk_sessoes primary key (id_sessao),
    constraint fk_sessoes_filmes foreign key (id_filme)
        references public.filmes (id_filme)
        on delete restrict
        on update cascade,
    constraint chk_sessoes_sala check (sala > 0),
    constraint chk_sessoes_preco check (preco >= 0),
    constraint chk_sessoes_ingressos check (ingressos_vendidos >= 0)
);

create table public.clientes (
    id_cliente integer generated by default as identity,
    nome varchar(150) not null,
    cpf varchar(14) not null,
    email varchar(150) not null,
    telefone varchar(20),
    data_nascimento date,
    data_cadastro timestamp not null default current_timestamp,

    constraint pk_clientes primary key (id_cliente),
    constraint uq_clientes_cpf unique (cpf),
    constraint uq_clientes_email unique (email)
);

create table public.ingressos (
    id_ingresso integer generated by default as identity,
    id_cliente integer not null,
    id_sessao integer not null,
    assento varchar(10) not null,
    forma_pagamento varchar(30) not null,
    valor_pago numeric(10, 2) not null,
    data_compra timestamp not null default current_timestamp,

    constraint pk_ingressos primary key (id_ingresso),

    constraint fk_ingressos_clientes foreign key (id_cliente)
        references public.clientes (id_cliente)
        on delete restrict
        on update cascade,

    constraint fk_ingressos_sessoes foreign key (id_sessao)
        references public.sessoes (id_sessao)
        on delete restrict
        on update cascade,

    constraint chk_ingressos_valor check (valor_pago >= 0),

    constraint chk_ingressos_pagamento check (
        forma_pagamento in ('Pix', 'Dinheiro', 'Cartão de débito', 'Cartão de crédito')
    ),

    constraint uq_ingressos_sessao_assento unique (id_sessao, assento)
);