-- =====================================================
-- CineManager - Estrutura do banco de dados no Supabase
-- Execute este arquivo no SQL Editor do Supabase.
-- Atenção: as políticas RLS abaixo deixam o acesso aberto
-- para fins didáticos. Em aplicação real, use autenticação.
-- =====================================================

create table if not exists public.filmes (
    id_filme integer generated by default as identity primary key,
    titulo varchar(150) not null,
    genero varchar(80) not null,
    duracao integer not null check (duracao > 0),
    classificacao varchar(10) not null check (classificacao in ('Livre', '10', '12', '14', '16', '18')),
    diretor varchar(120) not null
);

create table if not exists public.sessoes (
    id_sessao integer generated by default as identity primary key,
    id_filme integer not null references public.filmes(id_filme) on update cascade on delete restrict,
    data_hora timestamp not null,
    sala integer not null check (sala > 0),
    preco numeric(10, 2) not null check (preco >= 0),
    ingressos_vendidos integer not null default 0 check (ingressos_vendidos >= 0)
);

create table if not exists public.clientes (
    id_cliente integer generated by default as identity primary key,
    nome varchar(150) not null,
    cpf varchar(14) not null unique,
    email varchar(150) not null unique,
    telefone varchar(20),
    data_nascimento date,
    data_cadastro timestamp not null default now()
);

create table if not exists public.ingressos (
    id_ingresso integer generated by default as identity primary key,
    id_cliente integer not null references public.clientes(id_cliente) on update cascade on delete restrict,
    id_sessao integer not null references public.sessoes(id_sessao) on update cascade on delete restrict,
    assento varchar(10) not null,
    forma_pagamento varchar(30) not null check (forma_pagamento in ('Pix', 'Dinheiro', 'Cartão de débito', 'Cartão de crédito')),
    valor_pago numeric(10, 2) not null check (valor_pago >= 0),
    data_compra timestamp not null default now(),
    constraint uq_ingresso_sessao_assento unique (id_sessao, assento)
);

create index if not exists idx_sessoes_id_filme on public.sessoes(id_filme);
create index if not exists idx_ingressos_id_cliente on public.ingressos(id_cliente);
create index if not exists idx_ingressos_id_sessao on public.ingressos(id_sessao);

-- Mantém sessoes.ingressos_vendidos coerente com a tabela ingressos.
create or replace function public.recalcular_ingressos_vendidos()
returns trigger
language plpgsql
as $$
begin
    if (TG_OP = 'INSERT') then
        update public.sessoes
        set ingressos_vendidos = (
            select count(*) from public.ingressos where id_sessao = NEW.id_sessao
        )
        where id_sessao = NEW.id_sessao;

        return NEW;
    end if;

    if (TG_OP = 'UPDATE') then
        update public.sessoes
        set ingressos_vendidos = (
            select count(*) from public.ingressos where id_sessao = NEW.id_sessao
        )
        where id_sessao = NEW.id_sessao;

        if (OLD.id_sessao <> NEW.id_sessao) then
            update public.sessoes
            set ingressos_vendidos = (
                select count(*) from public.ingressos where id_sessao = OLD.id_sessao
            )
            where id_sessao = OLD.id_sessao;
        end if;

        return NEW;
    end if;

    if (TG_OP = 'DELETE') then
        update public.sessoes
        set ingressos_vendidos = (
            select count(*) from public.ingressos where id_sessao = OLD.id_sessao
        )
        where id_sessao = OLD.id_sessao;

        return OLD;
    end if;

    return null;
end;
$$;

drop trigger if exists trg_recalcular_ingressos_vendidos on public.ingressos;

create trigger trg_recalcular_ingressos_vendidos
after insert or update or delete on public.ingressos
for each row
execute function public.recalcular_ingressos_vendidos();

-- RLS didático para permitir que o front-end estático acesse o Supabase.
alter table public.filmes enable row level security;
alter table public.sessoes enable row level security;
alter table public.clientes enable row level security;
alter table public.ingressos enable row level security;

drop policy if exists "select_filmes_publico" on public.filmes;
drop policy if exists "insert_filmes_publico" on public.filmes;
drop policy if exists "update_filmes_publico" on public.filmes;
drop policy if exists "delete_filmes_publico" on public.filmes;

create policy "select_filmes_publico" on public.filmes for select to anon, authenticated using (true);
create policy "insert_filmes_publico" on public.filmes for insert to anon, authenticated with check (true);
create policy "update_filmes_publico" on public.filmes for update to anon, authenticated using (true) with check (true);
create policy "delete_filmes_publico" on public.filmes for delete to anon, authenticated using (true);

drop policy if exists "select_sessoes_publico" on public.sessoes;
drop policy if exists "insert_sessoes_publico" on public.sessoes;
drop policy if exists "update_sessoes_publico" on public.sessoes;
drop policy if exists "delete_sessoes_publico" on public.sessoes;

create policy "select_sessoes_publico" on public.sessoes for select to anon, authenticated using (true);
create policy "insert_sessoes_publico" on public.sessoes for insert to anon, authenticated with check (true);
create policy "update_sessoes_publico" on public.sessoes for update to anon, authenticated using (true) with check (true);
create policy "delete_sessoes_publico" on public.sessoes for delete to anon, authenticated using (true);

drop policy if exists "select_clientes_publico" on public.clientes;
drop policy if exists "insert_clientes_publico" on public.clientes;
drop policy if exists "update_clientes_publico" on public.clientes;
drop policy if exists "delete_clientes_publico" on public.clientes;

create policy "select_clientes_publico" on public.clientes for select to anon, authenticated using (true);
create policy "insert_clientes_publico" on public.clientes for insert to anon, authenticated with check (true);
create policy "update_clientes_publico" on public.clientes for update to anon, authenticated using (true) with check (true);
create policy "delete_clientes_publico" on public.clientes for delete to anon, authenticated using (true);

drop policy if exists "select_ingressos_publico" on public.ingressos;
drop policy if exists "insert_ingressos_publico" on public.ingressos;
drop policy if exists "update_ingressos_publico" on public.ingressos;
drop policy if exists "delete_ingressos_publico" on public.ingressos;

create policy "select_ingressos_publico" on public.ingressos for select to anon, authenticated using (true);
create policy "insert_ingressos_publico" on public.ingressos for insert to anon, authenticated with check (true);
create policy "update_ingressos_publico" on public.ingressos for update to anon, authenticated using (true) with check (true);
create policy "delete_ingressos_publico" on public.ingressos for delete to anon, authenticated using (true);
